version: "3.8"
services:
  postgres:
    image: postgres:12-alpine
    restart: always
    volumes:
      - nt-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: nestjs-test
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
volumes:
  nt-postgres-data:
